<a href="https://colab.research.google.com/github/Madhukar-Palakaveeti/deep_learning/blob/main/nninitial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
a = np.array([1,2,3,4])
b = np.array([[1,2,3,4],[5,6,7,8]])
c = np.array([[[1,2,3,4],[5,6,7,8]],[[2,3,4,5],[4,5,6,7]]])
print(a.shape)
print(b.shape)
print(c.shape)

(4,)
(2, 4)
(2, 2, 4)


In [ ]:
z = np.zeros([3,2,4])
print(z)
print(z.shape)

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]]]
(3, 2, 4)


In [ ]:
print(np.dot(b,a))
print(np.dot(c,a))

[30 70]
[[30 70]
 [40 60]]


In [ ]:
I = np.identity(4)
print(I)
print(c)
print(I.shape)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[[1 2 3 4]
  [5 6 7 8]]

 [[2 3 4 5]
  [4 5 6 7]]]
(4, 4)


In [ ]:
print(np.dot(c,I))

[[[1. 2. 3. 4.]
  [5. 6. 7. 8.]]

 [[2. 3. 4. 5.]
  [4. 5. 6. 7.]]]


In [ ]:
inputs = [1,2,3,2.5]
weights = [[0.2,0.8,-0.5,1.0],[0.5,-0.91,0.26,-0.5],[-0.26,-0.27,0.17,0.87]]
biases = [2,3,0.5]
print(np.dot(weights,inputs)+biases)

[4.8   1.21  2.385]


In [ ]:
X = np.array([[1,2,3,2.5],[2.0,5.0,-1.0,2.0],[-1.5,2.7,3.3,-0.8]])
print(X)

[[ 1.   2.   3.   2.5]
 [ 2.   5.  -1.   2. ]
 [-1.5  2.7  3.3 -0.8]]


In [ ]:
np.random.seed(0)


In [51]:
class Layer_Dense:
  def __init__(self,n_inputs,n_neurons):
    self.weights = 0.10 * np.random.randn(n_inputs,n_neurons)
    self.biases = np.zeros((1,n_neurons))

  def forward(self,inputs):
    self.output = np.dot(inputs, self.weights)+ self.biases

class Activation_ReLU:
  def forward(self,inputs):
    self.output = np.maximum(0,inputs)

class Activation_FakeSoftmax:
  def forward(self,inputs):
    exp_values = np.exp(inputs)
    probabilities = exp_values/np.sum(exp_values,axis=1,keepdims=True)
    self.output = probabilities

class Activation_Softmax:
  def forward(self,inputs):
    exp_values = np.exp(inputs - np.max(inputs,axis=1,keepdims=True))
    probabilities = exp_values/np.sum(exp_values,axis=1,keepdims=True)
    self.output = probabilities



In [ ]:
!pip install nnfs

In [ ]:
import nnfs
nnfs.init()
from nnfs.datasets import spiral_data

In [ ]:
X, y = spiral_data(samples=100, classes=3)

In [53]:
fake_layer = Layer_Dense(2,5)
fake_layer.forward(X)
# activation1 = Activation_ReLU()
# activation1.forward(layer1.output)
# print(activation1.output[:5])
activation2 = Activation_FakeSoftmax()
activation2.forward(fake_layer.output)
print("Fake Softmax")
print(activation2.output[:5])

activation3 = Activation_Softmax()
activation3.forward(fake_layer.output)
print("Softmax")
print(activation3.output[:5])


Fake Softmax
[[0.2        0.2        0.2        0.2        0.2       ]
 [0.20006417 0.19994867 0.20017552 0.1998886  0.19992304]
 [0.20016704 0.19988662 0.20027584 0.19973189 0.19993868]
 [0.20025529 0.19986759 0.20005466 0.1996346  0.2001879 ]
 [0.20034951 0.19981185 0.20013618 0.19949242 0.20020999]]
Softmax
[[0.2        0.2        0.2        0.2        0.2       ]
 [0.20006417 0.19994868 0.20017554 0.1998886  0.19992304]
 [0.20016702 0.19988658 0.20027582 0.19973187 0.19993867]
 [0.20025527 0.19986758 0.20005466 0.19963458 0.2001879 ]
 [0.20034952 0.19981186 0.2001362  0.19949245 0.20020999]]


In [55]:
# @title Implementing the neural network with two layers and two activation functions
layer1 = Layer_Dense(2,5)
activation1 = Activation_ReLU()

layer2 = Layer_Dense(5,3)
activation2 = Activation_Softmax()

layer1.forward(X)
activation1.forward(layer1.output)

layer2.forward(activation1.output)
activation2.forward(layer2.output)
print(activation2.output[:5])

[[0.33333334 0.33333334 0.33333334]
 [0.33334082 0.3333177  0.33334148]
 [0.33338886 0.33322498 0.33338612]
 [0.33351925 0.3330178  0.33346298]
 [0.3335719  0.33292595 0.33350214]]


In [62]:
# @title LOSS
#categorical_crossentropy for multiclass classification
# mean_squared_error for regression
import math
target_output = [1,0,0]
y_pred = [0.7,0.2,0.1]
loss = -(math.log(y_pred[0]) * target_output[0] + math.log(y_pred[1]) * target_output[1] + math.log(y_pred[2]) * target_output[2])
print(loss)

0.35667494393873245
